CREATE DATABASE IF NOT EXISTS `charity_app`;
USE `charity_app`;

CREATE TABLE IF NOT EXISTS `user` (
  user_id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  location VARCHAR(255),
  image VARCHAR(255),
  device_token VARCHAR(512),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS item (
  item_id INT PRIMARY KEY AUTO_INCREMENT,
  seller_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100),
  price DECIMAL(10, 2),
  status VARCHAR(50) DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (seller_id) REFERENCES `user`(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `transaction` (
  transaction_id INT PRIMARY KEY AUTO_INCREMENT,
  buyer_id INT NOT NULL,
  seller_id INT NOT NULL,
  item_id INT NOT NULL,
  amount DECIMAL(10, 2),
  type VARCHAR(50),
  status VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (buyer_id) REFERENCES `user`(user_id) ON DELETE CASCADE,
  FOREIGN KEY (seller_id) REFERENCES `user`(user_id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES item(item_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS charity (
  charity_id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  address VARCHAR(255),
  phone VARCHAR(20),
  email VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS donation (
  donation_id INT PRIMARY KEY AUTO_INCREMENT,
  donor_id INT NOT NULL,
  charity_id INT NOT NULL,
  item_id INT,
  status VARCHAR(50),
  gift_location VARCHAR(255),
  impact TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (donor_id) REFERENCES `user`(user_id) ON DELETE CASCADE,
  FOREIGN KEY (charity_id) REFERENCES charity(charity_id) ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES item(item_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS conversation (
  conversation_id INT PRIMARY KEY AUTO_INCREMENT,
  participant_one_id INT NOT NULL,
  participant_two_id INT,
  charity_id INT,
  item_id INT,
  context_type VARCHAR(50) NOT NULL DEFAULT 'sale',
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  last_message_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (participant_one_id) REFERENCES `user`(user_id) ON DELETE CASCADE,
  FOREIGN KEY (participant_two_id) REFERENCES `user`(user_id) ON DELETE SET NULL,
  FOREIGN KEY (charity_id) REFERENCES charity(charity_id) ON DELETE SET NULL,
  FOREIGN KEY (item_id) REFERENCES item(item_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS message (
  message_id INT PRIMARY KEY AUTO_INCREMENT,
  sender_id INT NOT NULL,
  receiver_id INT NOT NULL,
  conversation_id INT,
  item_id INT,
  content TEXT NOT NULL,
  encrypted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (sender_id) REFERENCES `user`(user_id) ON DELETE CASCADE,
  FOREIGN KEY (receiver_id) REFERENCES `user`(user_id) ON DELETE CASCADE,
  FOREIGN KEY (conversation_id) REFERENCES conversation(conversation_id) ON DELETE SET NULL,
  FOREIGN KEY (item_id) REFERENCES item(item_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS chatbot_query (
  query_id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  query TEXT NOT NULL,
  response TEXT,
  intent VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES `user`(user_id) ON DELETE CASCADE
);
